### ISSUE TITLE
Why are we exposing ports in docker-compose.yml ?

### ISSUE THREAD

**Issue by viktorsmari** [thingful/decode-system-test#4]
Why do we need to expose all the ports like postgres 5432?
* This means they will be accessible on the the host unless the host installs and configures some kind of firewall.
* All the containers are on the same internal Docker network, so they don't need to expose all the ports

**Comment by smulube** [comment]
That is absolutely correct - I will remove. I only had the postgres port exposed in order to debug some stuff using psql early one, but no need for postgres to be visible now.

I'm interested to know how you will be running these components for "real" so to speak. Are you using something heavy like Kubernetes or something simpler? This compose file was really just intended to demo the components operating together locally so I hadn't necessarily written it with real deployment in mind.

For example in this repo we don't currently give any concern to things like passing in TLS certificates, or running the services on a publicly accessible domain, etc. etc. The servers are set up to support TLS btw  but the certificates would need to be copied into the container and then the servers then started with the appropriate flags.

**Comment by viktorsmari** [comment]
We actually run our infra using docker-compose, the setup is here:
https://github.com/fablabbcn/smartcitizen-api

But we have Cassandra and mqtt on their own servers.
TLS is currently with Cloudflare, but on other projects we have also used an nginx + Lets Encrypt containers to handle this for us
