### ISSUE TITLE
Demo app not connecting to WebSockets

### ISSUE THREAD

**Issue by viktorsmari** [thingful/decode-system-test#6]
If you look at the developer console at:
http://decode.smartcitizen.me:4001/policies

```
WebSocket connection to 'ws://decode.smartcitizen.me:4001/socket/websocket?vsn=2.0.0' failed: Error during WebSocket handshake: Unexpected response code: 403
```

**Comment by smulube** [comment]
Hi @viktorsmari - sorry I didn't see this - if you tag me I should hopefully notice quicker. Another way of getting my attention would be via the Telegram group which I normally have open. I think Guillem can add you if you aren't already a member.

Here I think the Phoenix js socket by default is configured to only allow connections from the host it expects as the origin. On the server side this value is read from the `HOST` environment variable, so to make the socket connection work you need to set `HOST` to be `decode.smartcitizen.me`.

Hopefully with this change we should see the socket connecting.

**Comment by smulube** [comment]
This is the source of the demo app btw: https://github.com/thingful/decode-demo

**Comment by viktorsmari** [comment]
Confirmed that this solved the issue. :+1: 

It would be nice to have a `env_file: .env` in the `docker-compose.yml` and gitignore the `.env` file.

Then people can pull changes to their machines, without having to stash it. And having their own personal config in the `.env` file.

Now for example I have modified the docker-compose with the `HOST` variable, so next time I pull changes I need to remove those changes, and re-apply them.

**Comment by smulube** [comment]
ok that's great. 

Yes, that sounds like a perfectly reasonable suggestion. Can I just check something - is this compose config what you will actually be running in production so to speak, or are you taking from here to add to another larger configuration? I only ask because it might be worth decoupling the demo app from the rest in that case, as I will likely need to iterate a bunch of changes to that app once we get some more insight from the crypto partners on the changes that it needs.

In other news I have been working on a little python script which attempts to exercise all the endpoints and verify they are working properly as requested by Guillem to aid your verification that the components are all hooked up to each other correctly. Will share with you as soon as I have something working.

**Comment by viktorsmari** [comment]
We would like to run this in production with docker-compose, since we have experience with that.

Unless you want to recommend another approach?

**Comment by smulube** [comment]
We've only run docker images in a production setup on either Heroku (for quick and dirty), or AWS ECS for more involved setups. If you have an existing infrastructure that you are comfortable with then I don't think there is a compelling argument to change to one of the above.

However there might be an argument that we would deploy the demo UI application to Heroku, so I can just push changes without having to bug  you all the time to do that, but that's something we could discuss separately.

I just had a glance at the compose documentation on production use (https://docs.docker.com/compose/production/), and perhaps it would be a good idea to update this repo to create separate `production.yml` and `development.yml` configurations as it seems to me they have slightly different concerns
